### ISSUE TITLE
can i use myesp8266

### ISSUE THREAD

**Issue by abhinav596** [DoctorEenot/DUCOAndroidMiner#12]
can i use myesp8266 in this app to get more hash rate ??

**Comment by DoctorEenot** [comment]
That's an Android miner, I don't see a correlation between esp and a phone.

**Comment by BastelPichi** [comment]
Simply connect an ESP8266 with the code on it to an phone, download termux or any other python terminal emulator, an from there run the AVR Miner you can download from the official page.
