### ISSUE TITLE
Android cli use

### ISSUE THREAD

**Issue by hhjjj75** [DoctorEenot/DUCOAndroidMiner#3]
Can you add version so it can be used from android shell.
So i have 3 android phones and i wanted to run it from adb shell. So all 3 androids could mine easily duino coin :)

**Comment by DoctorEenot** [comment]
I had no intent on making cli version, and I am pretty sure you can interact with app via adb anyway. But maybe later I will make cli version, but I don't see any benefit on doing so, as I wrote you can interact with app via adb.

**Comment by DoctorEenot** [comment]
After some thoughts, I decided it is not an optimal solution to create CLI version. Source of miner is available for free, so feel free to use it.
