### ISSUE TITLE
Totally app failure

### ISSUE THREAD

**Issue by Manishmg3994** [DoctorEenot/DUCOAndroidMiner#7]
Dear All Developer ,Your Android app is not in service, please resolve all issues fast .Also there is one suggestion to permote your plateform ,the suggestion is Why not we develop an .aix file which is used on all app inventor plateform such as KODULAR ,NIOTRON,and all app inventor plateform.Please focus on this issue and also develop an .aix extension for me to mine more 
My user name is :-mg3994
If you permit or do create .aix extension ,please do book appointment is you are having any problem on my website [https://indianlegionhackdroid.wordpress.com/](https://indianlegionhackdroid.wordpress.com/)

**Comment by DoctorEenot** [comment]
Hello, issues with connection were resolved, I have no intent to create .aix file, source code of miner is available for free, fell free to used however you want.
